# Generated by Django 3.0.6 on 2020-05-27 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('architect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('عنوان', models.CharField(max_length=200)),
                ('design_upload_date', models.DateTimeField()),
                ('تاریخ_آپلود_طرح', models.DateTimeField()),
                ('design_date', models.DateTimeField(default=datetime.datetime.now)),
                ('تاریخ_طراحی', models.DateTimeField(default=datetime.datetime.now)),
                ('software_tool', models.CharField(default='Revit / 3DsMax / Lumion / Photoshop / Autocad', max_length=200)),
                ('نرم_افزارهای_مورد_استفاده', models.CharField(default='Revit / 3DsMax / Lumion / Photoshop / Autocad', max_length=200)),
                ('description', models.TextField(default='please add at least 10 words')),
                ('توضیحات', models.TextField(default='لطفا حداقل ده کلمه وارد کنید')),
                ('photo_main', models.ImageField(upload_to='photos/designes/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos/designes/%Y/%m/%d')),
                ('published', models.BooleanField(default=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='architect.Architect')),
            ],
        ),
    ]
