# Generated by Django 3.0.6 on 2020-05-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('درباره_ما', models.TextField(default='درباره ما')),
                ('phone', models.CharField(max_length=50)),
                ('موبایل', models.CharField(max_length=50)),
                ('office_phone', models.CharField(max_length=50)),
                ('تلفن_شرکت', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('آدرس', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('ایمیل', models.EmailField(max_length=254)),
                ('site_develoepr', models.BooleanField(default=True)),
            ],
        ),
    ]
