# Generated by Django 3.0.6 on 2020-05-27 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('اسم', models.CharField(max_length=200)),
                ('education', models.CharField(choices=[('فوق دیپلم', 'فوق دیپلم'), ('لیسانس ', 'لیسانس '), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا ', 'دکترا ')], default='Undergraduate', max_length=20)),
                ('تحصیلات', models.CharField(choices=[('Associate', 'Associate'), ('Undergraduate ', 'Undergraduate '), ('Master', 'Master'), ('Doctorate ', 'Doctorate ')], default='لیسانس', max_length=20)),
                ('background', models.TextField()),
                ('سابقه', models.TextField()),
                ('software_tools', models.TextField(default='Revit / 3DsMax / Photoshop / Lumion / Autocad')),
                ('مسلط_به_نرم_افزار_های', models.TextField(default='Revit / 3DsMax / Photoshop / Lumion / Autocad')),
                ('phone', models.CharField(max_length=50)),
                ('موبایل', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/atchitects/%Y/%m/%d')),
                ('hired_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('تاریخ_استخدام', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
