# Generated by Django 3.0.6 on 2020-05-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='education',
            field=models.CharField(choices=[('Associate', 'Associate'), ('Undergraduate ', 'Undergraduate '), ('Master', 'Master'), ('Doctorate ', 'Doctorate ')], default='Undergraduate', max_length=20),
        ),
        migrations.AlterField(
            model_name='architect',
            name='تحصیلات',
            field=models.CharField(choices=[('فوق دیپلم', 'فوق دیپلم'), ('لیسانس ', 'لیسانس '), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا ', 'دکترا ')], default='لیسانس', max_length=20),
        ),
    ]
